// Generated from STRUCTURE/BUILD_GUIDE/ROUTES.md by scripts/route-stages.py — do not edit by hand.

export const ROUTE_STAGES: Record<string, string> = {
  "/unauthorized": "U0 · Foundation",
  "/not-found": "U0 · Foundation",
  "/server-error": "U0 · Foundation",
  "/maintenance": "U0 · Foundation",
  "/offline": "U0 · Foundation",
  "/": "U1 · Public & marketing",
  "/about": "U1 · Public & marketing",
  "/how-it-works": "U1 · Public & marketing",
  "/pricing": "U1 · Public & marketing",
  "/blog": "U1 · Public & marketing",
  "/blog/[slug]": "U1 · Public & marketing",
  "/contact": "U1 · Public & marketing",
  "/faq": "U1 · Public & marketing",
  "/privacy": "U1 · Public & marketing",
  "/terms": "U1 · Public & marketing",
  "/search": "U1 · Public & marketing",
  "/auth/sign-in": "U2 · Auth (mocked)",
  "/auth/sign-up/candidate": "U2 · Auth (mocked)",
  "/auth/sign-up/employer": "U2 · Auth (mocked)",
  "/auth/sign-up/provider": "U2 · Auth (mocked)",
  "/auth/choose-role": "U2 · Auth (mocked)",
  "/auth/forgot-password": "U2 · Auth (mocked)",
  "/auth/reset-password": "U2 · Auth (mocked)",
  "/auth/verify-email": "U2 · Auth (mocked)",
  "/auth/verify-email/confirm   (route handler: consumes the emailed token, then redirects to /auth/verify-email)": "U2 · Auth (mocked)",
  "/billing/checkout": "U2 · Auth (mocked)",
  "/dashboard": "U3 · Candidate core",
  "/onboarding": "U3 · Candidate core",
  "/onboarding/personal": "U3 · Candidate core",
  "/onboarding/visa": "U3 · Candidate core",
  "/onboarding/education": "U3 · Candidate core",
  "/onboarding/experience": "U3 · Candidate core",
  "/onboarding/skills": "U3 · Candidate core",
  "/onboarding/preferences": "U3 · Candidate core",
  "/onboarding/personality-cv": "U3 · Candidate core",
  "/onboarding/review": "U3 · Candidate core",
  "/onboarding/complete": "U3 · Candidate core",
  "/profile": "U3 · Candidate core",
  "/profile/edit": "U3 · Candidate core",
  "/profile/experience/[experienceId]": "U3 · Candidate core",
  "/profile/skills": "U3 · Candidate core",
  "/profile/visa": "U3 · Candidate core",
  "/profile/preferences": "U3 · Candidate core",
  "/profile/documents": "U3 · Candidate core",
  "/settings": "U3 · Candidate core",
  "/settings/notifications": "U3 · Candidate core",
  "/ai-cv": "U5 · Candidate tools",
  "/ai-cv/generate": "U5 · Candidate tools",
  "/ai-cv/[cvId]": "U5 · Candidate tools",
  "/ai-cv/[cvId]/edit": "U5 · Candidate tools",
  "/ai-cv/history": "U5 · Candidate tools",
  "/personality-cv": "U5 · Candidate tools",
  "/personality-cv/record": "U5 · Candidate tools",
  "/personality-cv/preview": "U5 · Candidate tools",
  "/personality-cv/settings": "U5 · Candidate tools",
  "/signia": "U5 · Candidate tools",
  "/signia/builder": "U5 · Candidate tools",
  "/signia/projects/[projectId]": "U5 · Candidate tools",
  "/signia/media": "U5 · Candidate tools",
  "/signia/social-links": "U5 · Candidate tools",
  "/signia/preview": "U5 · Candidate tools",
  "/s/[handle]": "U5 · Candidate tools",
  "/applications/insights": "U5 · Candidate tools",
  "/messages": "U5 · Candidate tools",
  "/messages/[threadId]": "U5 · Candidate tools",
  "/notifications": "U5 · Candidate tools",
  "/billing": "U5 · Candidate tools",
  "/programs": "U6 · 02 Universities",
  "/programs/[levelSlug]": "U6 · 02 Universities",
  "/programs/[levelSlug]/[fieldSlug]": "U6 · 02 Universities",
  "/universities": "U6 · 02 Universities",
  "/universities/search": "U6 · 02 Universities",
  "/universities/country/[countrySlug]": "U6 · 02 Universities",
  "/universities/[universitySlug]": "U6 · 02 Universities",
  "/universities/[universitySlug]/programs": "U6 · 02 Universities",
  "/universities/[universitySlug]/programs/[programSlug]": "U6 · 02 Universities",
  "/universities/[universitySlug]/eligibility": "U6 · 02 Universities",
  "/universities/[universitySlug]/apply": "U6 · 02 Universities",
  "/universities/saved": "U6 · 02 Universities",
  "/universities/compare": "U6 · 02 Universities",
  "/universities/dashboard": "U6 · 02 Universities",
  "/universities/applications": "U6 · 02 Universities",
  "/universities/applications/[applicationId]": "U6 · 02 Universities",
  "/saved": "U6 · 02 Universities",
  "/applications": "U6 · 02 Universities",
  "/applications/[applicationId]": "U6 · 02 Universities",
  "/applications/drafts": "U6 · 02 Universities",
  "/scholarships": "U7 · 03 Scholarships",
  "/scholarships/search": "U7 · 03 Scholarships",
  "/scholarships/[scholarshipSlug]": "U7 · 03 Scholarships",
  "/scholarships/[scholarshipSlug]/eligibility": "U7 · 03 Scholarships",
  "/scholarships/[scholarshipSlug]/apply": "U7 · 03 Scholarships",
  "/scholarships/matcher": "U7 · 03 Scholarships",
  "/scholarships/saved": "U7 · 03 Scholarships",
  "/scholarships/applications": "U7 · 03 Scholarships",
  "/scholarships/applications/[applicationId]": "U7 · 03 Scholarships",
  "/scholarships/applications/[applicationId]/answers": "U7 · 03 Scholarships",
  "/scholarships/deadlines": "U7 · 03 Scholarships",
  "/scholarships/verification": "U7 · 03 Scholarships",
  "/providers/onboarding": "U8 · Provider portals",
  "/providers/dashboard": "U8 · Provider portals",
  "/providers/opportunities": "U8 · Provider portals",
  "/providers/opportunities/new": "U8 · Provider portals",
  "/providers/opportunities/[opportunityId]/edit": "U8 · Provider portals",
  "/providers/applications": "U8 · Provider portals",
  "/providers/applications/[applicationId]": "U8 · Provider portals",
  "/providers/team": "U8 · Provider portals",
  "/providers/settings": "U8 · Provider portals",
  "/apply-agent": "U9 · 09 AI Apply Agent",
  "/apply-agent/setup": "U9 · 09 AI Apply Agent",
  "/apply-agent/rules": "U9 · 09 AI Apply Agent",
  "/apply-agent/queue": "U9 · 09 AI Apply Agent",
  "/apply-agent/queue/add": "U9 · 09 AI Apply Agent",
  "/apply-agent/runs": "U9 · 09 AI Apply Agent",
  "/apply-agent/runs/[runId]": "U9 · 09 AI Apply Agent",
  "/apply-agent/performance": "U9 · 09 AI Apply Agent",
  "/apply-agent/pricing": "U9 · 09 AI Apply Agent",
  "/apply-for-me": "U10 · 10 Apply For Me",
  "/apply-for-me/board": "U10 · 10 Apply For Me",
  "/apply-for-me/proposals/new": "U10 · 10 Apply For Me",
  "/apply-for-me/proposals/[proposalId]": "U10 · 10 Apply For Me",
  "/apply-for-me/campaigns": "U10 · 10 Apply For Me",
  "/apply-for-me/campaigns/[contractId]": "U10 · 10 Apply For Me",
  "/apply-for-me/messages": "U10 · 10 Apply For Me",
  "/apply-for-me/payments": "U10 · 10 Apply For Me",
  "/forwarder/onboarding": "U10 · 10 Apply For Me",
  "/forwarder/dashboard": "U10 · 10 Apply For Me",
  "/forwarder/contracts": "U10 · 10 Apply For Me",
  "/forwarder/contracts/[contractId]": "U10 · 10 Apply For Me",
  "/admin/discovery": "U11 · 11 Discovery Engine",
  "/admin/discovery/categories": "U11 · 11 Discovery Engine",
  "/admin/discovery/sources": "U11 · 11 Discovery Engine",
  "/admin/discovery/sources/[sourceId]": "U11 · 11 Discovery Engine",
  "/admin/discovery/queue": "U11 · 11 Discovery Engine",
  "/admin/discovery/queue/[itemId]": "U11 · 11 Discovery Engine",
  "/admin/discovery/freshness": "U11 · 11 Discovery Engine",
  "/admin/discovery/coverage": "U11 · 11 Discovery Engine",
  "/relocation": "U12 · 12 Relocation",
  "/relocation/[countrySlug]": "U12 · 12 Relocation",
  "/pilots/apply": "U12 · 12 Relocation",
  "/journey": "U12 · 12 Relocation",
  "/journey/setup": "U12 · 12 Relocation",
  "/journey/pre-arrival": "U12 · 12 Relocation",
  "/journey/post-arrival": "U12 · 12 Relocation",
  "/journey/steps/[stepId]": "U12 · 12 Relocation",
  "/journey/costs": "U12 · 12 Relocation",
  "/journey/travel": "U12 · 12 Relocation",
  "/journey/cohort": "U12 · 12 Relocation",
  "/journey/handsoff": "U12 · 12 Relocation",
  "/accommodation": "U12 · 12 Relocation",
  "/accommodation/[listingId]": "U12 · 12 Relocation",
  "/accommodation/[listingId]/book": "U12 · 12 Relocation",
  "/accommodation/bookings": "U12 · 12 Relocation",
  "/accommodation/bookings/[bookingId]": "U12 · 12 Relocation",
  "/roommates": "U12 · 12 Relocation",
  "/roommates/profile": "U12 · 12 Relocation",
  "/roommates/requests": "U12 · 12 Relocation",
  "/communities": "U12 · 12 Relocation",
  "/communities/[communityId]": "U12 · 12 Relocation",
  "/communities/suggest": "U12 · 12 Relocation",
  "/city-guide/[citySlug]": "U12 · 12 Relocation",
  "/pilots": "U12 · 12 Relocation",
  "/pilots/awards": "U12 · 12 Relocation",
  "/pilots/awards/vote": "U12 · 12 Relocation",
  "/pilots/[pilotId]": "U12 · 12 Relocation",
  "/pilots/bookings": "U12 · 12 Relocation",
  "/pilots/bookings/[bookingId]": "U12 · 12 Relocation",
  "/support": "U12 · 12 Relocation",
  "/support/join": "U12 · 12 Relocation",
  "/support/cases/new": "U12 · 12 Relocation",
  "/support/cases/[caseId]": "U12 · 12 Relocation",
  "/pilot/onboarding": "U13 · Relocation operations",
  "/pilot/dashboard": "U13 · Relocation operations",
  "/pilot/requests": "U13 · Relocation operations",
  "/pilot/bookings/[bookingId]": "U13 · Relocation operations",
  "/pilot/cohorts": "U13 · Relocation operations",
  "/pilot/cohorts/[cohortId]": "U13 · Relocation operations",
  "/pilot/cases": "U13 · Relocation operations",
  "/pilot/earnings": "U13 · Relocation operations",
  "/pilot/referrals": "U13 · Relocation operations",
  "/pilot/profile": "U13 · Relocation operations",
  "/housing/onboarding": "U13 · Relocation operations",
  "/housing/dashboard": "U13 · Relocation operations",
  "/housing/listings": "U13 · Relocation operations",
  "/housing/listings/new": "U13 · Relocation operations",
  "/housing/listings/[listingId]": "U13 · Relocation operations",
  "/housing/bookings": "U13 · Relocation operations",
  "/housing/bookings/[bookingId]": "U13 · Relocation operations",
  "/housing/payouts": "U13 · Relocation operations",
  "/admin/relocation": "U13 · Relocation operations",
  "/admin/relocation/countries/[countryCode]": "U13 · Relocation operations",
  "/admin/relocation/steps/[stepId]": "U13 · Relocation operations",
  "/admin/relocation/embassies": "U13 · Relocation operations",
  "/admin/relocation/embassies/[embassyId]": "U13 · Relocation operations",
  "/admin/relocation/preview": "U13 · Relocation operations",
  "/admin/relocation/reviews": "U13 · Relocation operations",
  "/admin/relocation/costs": "U13 · Relocation operations",
  "/admin/communities": "U13 · Relocation operations",
  "/admin/pilots": "U13 · Relocation operations",
  "/admin/pilots/[pilotId]": "U13 · Relocation operations",
  "/admin/pilot-commissions": "U13 · Relocation operations",
  "/admin/pilot-awards": "U13 · Relocation operations",
  "/admin/cohorts": "U13 · Relocation operations",
  "/admin/accommodation": "U13 · Relocation operations",
  "/admin/settlements": "U13 · Relocation operations",
  "/admin/support-cases": "U13 · Relocation operations",
  "/admin/support-cases/[caseId]": "U13 · Relocation operations",
  "/admin/partner-lawyers": "U13 · Relocation operations",
  "/migration-agencies": "U14 · 13 Migration Agencies",
  "/migration-agencies/search": "U14 · 13 Migration Agencies",
  "/migration-agencies/[agencySlug]": "U14 · 13 Migration Agencies",
  "/migration-agencies/services/[serviceId]": "U14 · 13 Migration Agencies",
  "/migration-agencies/book/[serviceId]": "U14 · 13 Migration Agencies",
  "/migration-agencies/dashboard": "U14 · 13 Migration Agencies",
  "/migration-agencies/appointments/[appointmentId]": "U14 · 13 Migration Agencies",
  "/migration-agencies/payments": "U14 · 13 Migration Agencies",
  "/migration-agencies/partners/onboarding": "U14 · 13 Migration Agencies",
  "/office/dashboard": "U14 · 13 Migration Agencies",
  "/office/services": "U14 · 13 Migration Agencies",
  "/office/appointments": "U14 · 13 Migration Agencies",
  "/partner-agency/dashboard": "U14 · 13 Migration Agencies",
  "/dashboard/jobs": "U15 · 14 Jobs — candidate (Pro)",
  "/dashboard/jobs/[jobId]": "U15 · 14 Jobs — candidate (Pro)",
  "/dashboard/jobs/saved": "U15 · 14 Jobs — candidate (Pro)",
  "/dashboard/jobs/post-study": "U15 · 14 Jobs — candidate (Pro)",
  "/applications/apply/[jobId]": "U15 · 14 Jobs — candidate (Pro)",
  "/applications/apply/[jobId]/review": "U15 · 14 Jobs — candidate (Pro)",
  "/employers": "U16 · Employers",
  "/for-employers": "U16 · Employers",
  "/employers/onboarding": "U16 · Employers",
  "/employers/onboarding/company": "U16 · Employers",
  "/employers/onboarding/hiring": "U16 · Employers",
  "/employers/onboarding/team": "U16 · Employers",
  "/employers/onboarding/complete": "U16 · Employers",
  "/employers/dashboard": "U16 · Employers",
  "/employers/company": "U16 · Employers",
  "/employers/jobs": "U16 · Employers",
  "/employers/jobs/new": "U16 · Employers",
  "/employers/jobs/[jobId]/edit": "U16 · Employers",
  "/employers/jobs/[jobId]/applicants": "U16 · Employers",
  "/employers/applications/[applicationId]": "U16 · Employers",
  "/employers/applications/[applicationId]/cv": "U16 · Employers",
  "/employers/candidates/[candidateId]": "U16 · Employers",
  "/employers/candidates/[candidateId]/personality-cv": "U16 · Employers",
  "/employers/candidates/[candidateId]/signia": "U16 · Employers",
  "/employers/signia": "U16 · Employers",
  "/employers/signia/compare": "U16 · Employers",
  "/employers/pipeline": "U16 · Employers",
  "/employers/screening-questions": "U16 · Employers",
  "/employers/messages": "U16 · Employers",
  "/employers/messages/[threadId]": "U16 · Employers",
  "/employers/notifications": "U16 · Employers",
  "/employers/analytics": "U16 · Employers",
  "/employers/jobs/[jobId]/analytics": "U16 · Employers",
  "/employers/team": "U16 · Employers",
  "/employers/settings": "U16 · Employers",
  "/employers/settings/notifications": "U16 · Employers",
  "/employers/billing": "U16 · Employers",
  "/employers/billing/checkout": "U16 · Employers",
  "/employers/work-eligibility": "U16 · Employers",
  "/admin": "U17 · Admin",
  "/admin/sign-in": "U17 · Admin",
  "/admin/users": "U17 · Admin",
  "/admin/users/[userId]": "U17 · Admin",
  "/admin/users/[userId]/profile": "U17 · Admin",
  "/admin/employers": "U17 · Admin",
  "/admin/employers/[employerId]": "U17 · Admin",
  "/admin/providers": "U17 · Admin",
  "/admin/providers/[providerId]": "U17 · Admin",
  "/admin/opportunities": "U17 · Admin",
  "/admin/jobs": "U17 · Admin",
  "/admin/universities": "U17 · Admin",
  "/admin/scholarships": "U17 · Admin",
  "/admin/applications": "U17 · Admin",
  "/admin/reports": "U17 · Admin",
  "/admin/ai-generations": "U17 · Admin",
  "/admin/ai-generations/cvs": "U17 · Admin",
  "/admin/ai-generations/applications": "U17 · Admin",
  "/admin/personality-cv": "U17 · Admin",
  "/admin/messages": "U17 · Admin",
  "/admin/notifications": "U17 · Admin",
  "/admin/subscriptions": "U17 · Admin",
  "/admin/analytics": "U17 · Admin",
  "/admin/blog": "U17 · Admin",
  "/admin/settings": "U17 · Admin",
};
